import express from "express";
import { getAdminDetails, loginAdmin } from "../controllers/admin/auth";
import { AdminAuth } from "../middleware/auth.middlware";
import { createMarket, deleteMarket, getAllMarkets, updateMarket } from "../controllers/admin/Market";
import { createMarketResult, deleteMarketResult, getAllMarketResults, updateMarketResult } from "../controllers/admin/Result";
const adminRoute = express.Router();
adminRoute.post("/login", loginAdmin);
adminRoute.get("/details", AdminAuth, getAdminDetails);
adminRoute.post("/create-market",AdminAuth, createMarket);
adminRoute.get("/market-list",AdminAuth, getAllMarkets);
adminRoute.put("/market-update/:id",AdminAuth, updateMarket);
adminRoute.delete("/market-delete/:id",AdminAuth, deleteMarket);
adminRoute.post("/create-market-result",AdminAuth, createMarketResult);
adminRoute.get("/result-list", AdminAuth,getAllMarketResults);
adminRoute.put("/result-update/:id",AdminAuth, updateMarketResult);
adminRoute.delete("/result-delete/:id",AdminAuth, deleteMarketResult);
export default adminRoute;