import express from "express";
import { userAuth } from "../middleware/auth.middlware";
import { getLiveResult, getMarketCalendar, getPivotMarketResults } from "../controllers/user/Result";
import { getAllMarkets } from "../controllers/user/Market";
const userRoute = express.Router();
userRoute.get("/result-stats", userAuth, getPivotMarketResults);
userRoute.get("/live-result", userAuth, getLiveResult);
userRoute.get("/get-market", userAuth, getAllMarkets);
userRoute.get("/get-calender", userAuth, getMarketCalendar);
export default userRoute;